my:
  appname: EurekaServer
  crd:
      port: 8081
  wtf:
      port: 8082
  sgd:
      port: 8083
  sgo:
      port: 8084
eureka:
 instance:
   instanceId: ${my.appname}-${server.port}
   appname: ${my.appname}
   preferIpAddress : true
 client:
   availabilityZones:
      UK: crd,wtf
      SG: sgo,sgd
   registerWithEureka: true
   fetchRemoteRegionsRegistry: UK,SG
   fetchRegistry: true
   healthcheck:
         enabled: true
   serviceUrl:
     crd: http://127.0.0.3:${my.crd.port}/eureka/
     wtf: http://127.0.0.3:${my.wtf.port}/eureka/
     sgd: http://127.0.0.3:${my.sgd.port}/eureka/
     sgo: http://127.0.0.3:${my.sgo.port}/eureka/
 server:
   waitTimeInMsWhenSyncEmpty: 0


---
spring:
  profiles: crd
server:
  port: ${my.crd.port}
eureka:
  client:
     region: UK

---
spring:
  profiles: wtf
server:
  port: ${my.wtf.port}
eureka:
  client:
     region: UK

---
spring:
  profiles: sgd
server:
  port: ${my.sgd.port}
eureka:
  client:
     region: SG

---
spring:
  profiles: sgo
server:
  port: ${my.sgo.port}
eureka:
  client:
     region: SG